### Save a new Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "text": "User registered",
  "datetime": "2026-01-22T10:15:00Z"
}

### Get all Events
GET http://localhost:3000/api/events